default_platform(:ios)

platform :ios do
  desc "Upload iOS App to App Store Connect / TestFlight"
  lane :upload_to_app_store_connect do
    upload_to_testflight(
      api_key_path: "api_key.json",
      ipa: "TryZonAI.ipa",
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end
end
