-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrj2fASZ6xuFJLh1p
NCJunV0w6NJOIeXNmLkbivA7n5egCgYIKoZIzj0DAQehRANCAAQRwxS0DA1gwjwE
aTFyPDCsAAamFWLG41fYD9FqJ/QqGPmmTzpP4ltX4SqTM3GqAh5miWJcrMskF8Lo
9aa6GXrr
-----END PRIVATE KEY-----