package com.jagtarapvtltd.tryzonai.ui.components

import androidx.compose.animation.*
import androidx.compose.animation.core.tween
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.jagtarapvtltd.tryzonai.ui.theme.PrimaryGold

data class TourStep(
    val icon: String,
    val title: String,
    val subtitle: String,
    val tip: String
)

@OptIn(ExperimentalAnimationApi::class)
@Composable
fun InteractiveTourModal(
    onDismiss: () -> Unit
) {
    val steps = listOf(
        TourStep("👋", "Welcome to TryZon AI", "Your personal AI Virtual Fitting Room Studio in seconds!", "Try on any clothing item virtually on your body photo before buying online."),
        TourStep("📸", "Step 1: Choose Your Photo", "Select your body photo or use our pre-loaded models", "Upload a clear full-length or upper body photo for realistic AI fitting results."),
        TourStep("👗", "Step 2: Select Outfit", "Pick garments from Catalog, Gallery, or paste links", "Paste product links from Myntra, Meesho, Amazon, Ajio or upload outfit screenshots."),
        TourStep("✨", "Step 3: Generate Try-On", "Tap 'Generate Virtual Try-On' to see the magic", "Our GPU AI engine fits the clothing texture & lighting onto your photo in 10s."),
        TourStep("❤️", "Step 4: Compare & Share", "Use Before/After slider & Google Lens", "Double-tap to save to Magic Closet, or tap Lens to buy matching outfits online."),
        TourStep("🎁", "Step 5: Daily Style Drops", "Daily AI Style notifications tailored for you", "Receive a fresh autogenerated outfit notification every morning at 9:00 AM!")
    )

    var currentStepIndex by remember { mutableStateOf(0) }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Text("🎓 Quick App Tour", fontWeight = FontWeight.Black, fontSize = 16.sp, color = PrimaryGold)
                    Spacer(modifier = Modifier.width(6.dp))
                    Text("(${currentStepIndex + 1}/${steps.size})", fontSize = 12.sp, color = MaterialTheme.colorScheme.onSurfaceVariant)
                }
                TextButton(onClick = onDismiss) {
                    Text("Skip Tour", fontSize = 12.sp, color = MaterialTheme.colorScheme.onSurfaceVariant)
                }
            }
        },
        text = {
            Column(
                modifier = Modifier.fillMaxWidth().padding(vertical = 4.dp),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                // Progress Dots Indicator
                Row(
                    horizontalArrangement = Arrangement.spacedBy(6.dp),
                    modifier = Modifier.padding(bottom = 16.dp)
                ) {
                    steps.indices.forEach { index ->
                        Box(
                            modifier = Modifier
                                .size(if (index == currentStepIndex) 10.dp else 6.dp)
                                .background(
                                    color = if (index == currentStepIndex) PrimaryGold else MaterialTheme.colorScheme.outline.copy(alpha = 0.3f),
                                    shape = CircleShape
                                )
                        )
                    }
                }

                // Animated Step Card Content
                AnimatedContent(
                    targetState = currentStepIndex,
                    transitionSpec = {
                        fadeIn(tween(300)) togetherWith fadeOut(tween(300))
                    },
                    label = "tour_step_animation"
                ) { stepIdx ->
                    val step = steps[stepIdx]
                    Column(
                        horizontalAlignment = Alignment.CenterHorizontally,
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Surface(
                            shape = CircleShape,
                            color = PrimaryGold.copy(alpha = 0.15f),
                            modifier = Modifier.size(72.dp)
                        ) {
                            Box(contentAlignment = Alignment.Center) {
                                Text(step.icon, fontSize = 36.sp)
                            }
                        }

                        Spacer(modifier = Modifier.height(14.dp))

                        Text(
                            step.title,
                            fontWeight = FontWeight.Black,
                            fontSize = 18.sp,
                            textAlign = TextAlign.Center,
                            color = MaterialTheme.colorScheme.onSurface
                        )

                        Spacer(modifier = Modifier.height(4.dp))

                        Text(
                            step.subtitle,
                            fontSize = 13.sp,
                            fontWeight = FontWeight.SemiBold,
                            textAlign = TextAlign.Center,
                            color = PrimaryGold
                        )

                        Spacer(modifier = Modifier.height(10.dp))

                        Surface(
                            color = MaterialTheme.colorScheme.surfaceVariant,
                            shape = RoundedCornerShape(14.dp),
                            modifier = Modifier.fillMaxWidth().border(1.dp, MaterialTheme.colorScheme.outline.copy(alpha = 0.15f), RoundedCornerShape(14.dp))
                        ) {
                            Text(
                                step.tip,
                                fontSize = 12.sp,
                                lineHeight = 18.sp,
                                textAlign = TextAlign.Center,
                                color = MaterialTheme.colorScheme.onSurfaceVariant,
                                modifier = Modifier.padding(12.dp)
                            )
                        }
                    }
                }
            }
        },
        confirmButton = {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                if (currentStepIndex > 0) {
                    OutlinedButton(
                        onClick = { currentStepIndex-- },
                        shape = RoundedCornerShape(12.dp)
                    ) {
                        Text("← Back", fontSize = 13.sp)
                    }
                } else {
                    Spacer(modifier = Modifier.width(1.dp))
                }

                ShimmeringButton(
                    text = if (currentStepIndex == steps.size - 1) "Get Started 🚀" else "Next Step →",
                    onClick = {
                        if (currentStepIndex < steps.size - 1) {
                            currentStepIndex++
                        } else {
                            onDismiss()
                        }
                    },
                    modifier = Modifier.height(44.dp)
                )
            }
        },
        containerColor = MaterialTheme.colorScheme.surface,
        shape = RoundedCornerShape(24.dp)
    )
}
