default_platform(:ios)

platform :ios do
  desc "Build Signed iOS App IPA & Upload to App Store Connect / TestFlight"
  lane :build_and_upload do
    project_path = File.expand_path("../TryZonAI.xcodeproj", __dir__)
    export_options_path = File.expand_path("../ExportOptions.plist", __dir__)
    auth_key_path = File.expand_path("../AuthKey_LF5HAF3NWP.p8", __dir__)
    output_dir = File.expand_path("..", __dir__)

    api_key = app_store_connect_api_key(
      key_id: "LF5HAF3NWP",
      issuer_id: "e5243ecc-3f1a-4093-aa87-5963eae05a08",
      key_filepath: auth_key_path,
      duration: 1200
    )

    build_app(
      project: project_path,
      scheme: "TryZonAI",
      destination: "generic/platform=iOS",
      export_method: "app-store",
      export_options: export_options_path,
      output_directory: output_dir,
      output_name: "TryZonAI.ipa",
      clean: true
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: "com.jagtarapvtltd.tryzonai",
      ipa: File.join(output_dir, "TryZonAI.ipa"),
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end
end
